apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::169193134380:user/pasjtene
      username: pasjtene
      groups:
        - system:masters
        - system:nodes
        