apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: jtbasic2-cluster2
  region: us-east-1

availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
nodeGroups:
  - name: jtng-1
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: false # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: jtng-2
    instanceType: m5.xlarge
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      publicKeyPath: ./myjtkey_pair.pub